[package]
name = "docbox-http"
version = "0.6.0"
edition = "2024"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Environment variables
dotenvy = "=0.15.7"

# Docbox core
docbox-core.workspace = true

# Asynchronous runtime & Helpers
tokio = { workspace = true, features = ["full"] }
futures.workspace = true

# HTTP server framework
axum = { version = "=0.8.8", features = ["multipart"] }

# Tower
tower = { version = "=0.5.3" }

# Typed multipart extraction
axum_typed_multipart = "=0.16.5"

# Validation & Axum validation integration
garde.workspace = true
axum-valid = { version = "=0.24.0", default-features = false, features = [
    "garde",
    "basic",
    "typed_multipart",
    "full_garde",
] }

# Error handling
thiserror.workspace = true

# Serialization and JSON
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

bytes.workspace = true

uuid.workspace = true

chrono.workspace = true

mime.workspace = true
mime_guess.workspace = true

utoipa.workspace = true
