[package]
name = "docbox-secrets"
version = "0.5.0"
edition = "2024"
description = "Docbox secret management abstraction"

license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Asynchronous runtime & Helpers
tokio = { workspace = true, features = ["sync"] }

# Error handling
thiserror.workspace = true

# Serialization and JSON
serde.workspace = true
serde_json.workspace = true

# Logging
tracing.workspace = true

# AWS Config
aws-config.workspace = true

# AWS Secrets Manager SDK
aws-sdk-secretsmanager = "1.98.0"

[dev-dependencies]
testcontainers = { workspace = true, features = ["http_wait"] }
tokio = { workspace = true, features = ["full"] }
